### ISSUE TITLE
continues scan without blocking and duplicate scan return

### ISSUE THREAD

**Issue by tibyanne** [GovindaPaliwal/AwesomeCodeScanner#1]
Hi Govinda;

1- when ever I scan a barcode the preview stops after getting the result, can you make it continues like when we scan a barcode we get result but the preview stay active.

2- a return method to block duplicate scans.

and what is the licence for this library?

**Comment by GovindaPaliwal** [comment]
Hi @iramuhammad 
Yes, i will try to add this feature.
And the licence is Apache 2.0.

**Comment by tibyanne** [comment]
@GovindaPaliwal 
Can I have your permission to make an extension for app inventor using this library?

**Comment by GovindaPaliwal** [comment]
> @GovindaPaliwal
> Can I have your permission to make an extension for app inventor using this library?

means ?

**Comment by tibyanne** [comment]
I want to make an extension for  MIT App Inventor using this library of yours, can I have your permission to do this?!

https://appinventor.mit.edu/

**Comment by GovindaPaliwal** [comment]
@iramuhammad 
Ohh, Yes you can use it. No problem

**Comment by tibyanne** [comment]
@GovindaPaliwal 
Thank you sir :)
